# File: services.yaml
# Note: Keep this filename comment for navigation and organization

test_connection:
  description: "Test connection to Overseerr and get basic information"
  fields: {}
  response:
    optional: true

check_media_status:
  description: "Check media status with LLM-optimized structured response"
  fields:
    title:
      description: "Movie or TV show title to search for"
      required: true
      selector:
        text:
  response:
    optional: true

add_media:
  description: "Add movie or TV show to Overseerr with LLM-optimized response (auto-detects type)"
  fields:
    title:
      description: "Movie or TV show title to search for and add"
      required: true
      selector:
        text:
  response:
    optional: true

search_media:
  description: "Search for movies and TV shows with LLM-optimized response (returns multiple results for selection)"
  fields:
    query:
      description: "Search query for movies or TV shows (can include titles, actors, genres, etc.)"
      required: true
      selector:
        text:
  response:
    optional: true

remove_media:
  description: "Remove media from Overseerr with LLM-optimized response (provide title OR media_id)"
  fields:
    title:
      description: "Movie or TV show title to search for and remove (will find media_id automatically)"
      required: false
      selector:
        text:
    media_id:
      description: "Direct media ID to remove (from mediaInfo.id in status checks)"
      required: false
      selector:
        text:
  response:
    optional: true

get_active_requests:
  description: "Get current active requests with LLM-optimized response (focuses on processing requests, ordered by date)"
  fields: {}
  response:
    optional: true