add_radarr_movie:
  description: "Add a movie to Radarr"
  fields:
    title:
      description: "Title of the movie"
      example: "Gladiator"

add_sonarr_tv_show:
  description: "Add a TV show to Sonarr"
  fields:
    title:
      description: "Title of the TV show"
      example: "Breaking Bad"

add_overseerr_movie:
  description: "Add a movie to Overseerr"
  fields:
    title:
      description: "Title of the movie"
      example: "Gladiator"

add_overseerr_tv_show:
  description: "Add a TV show to Overseerr"
  fields:
    title:
      description: "Title of the TV show"
      example: "Breaking Bad"

check_media_status:
  description: "Check the status of a movie or TV show in Overseerr with LLM-optimized response"
  fields:
    title:
      description: "Title of the movie or TV show to check"
      example: "The Matrix"
      required: true

remove_media:
  description: "Remove a movie or TV show from Overseerr by media ID"
  fields:
    media_id:
      description: "The internal Overseerr media ID (found in status checks)"
      example: "12345"
      required: true

get_active_requests:
  description: "Get all active requests from Overseerr with download progress and LLM guidance"
  fields: {}

search_media:
  description: "Search for movies or TV shows in Overseerr"
  fields:
    query:
      description: "Search query for movies or TV shows"
      example: "The Matrix"
      required: true

get_media_details:
  description: "Get detailed information about a specific movie or TV show"
  fields:
    media_type:
      description: "Type of media (movie or tv)"
      example: "movie"
      required: true
    tmdb_id:
      description: "TMDB ID of the media"
      example: "603"
      required: true