# File: services.yaml
# Note: Keep this filename comment for navigation and organization

test_connection:
  description: "Test connection to Overseerr and get basic information"
  fields: {}
  response:
    optional: true