# File: services.yaml
# Note: Keep this filename comment for navigation and organization

test_connection:
  description: "Test connection to Overseerr and get basic information"
  fields: {}
  response:
    optional: true

check_media_status:
  description: "Check media status with LLM-optimized structured response"
  fields:
    title:
      description: "Movie or TV show title to search for"
      required: true
      example: "The Dark Knight"
      selector:
        text:
  response:
    optional: true

add_media:
  description: "Add movie or TV show to Overseerr with LLM-optimized response (auto-detects type, supports season selection for TV shows)"
  fields:
    title:
      description: "Movie or TV show title to search for and add"
      required: true
      example: "Inception"
      selector:
        text:
    season:
      description: "For TV shows: season number (1, 2, 3) or natural language ('season two', 'remaining seasons', 'next season', 'all seasons'). Defaults to season 1 if not specified."
      required: false
      example: "remaining seasons"
      selector:
        text:
  response:
    optional: true

search_media:
  description: "Search for movies and TV shows with LLM-optimized response (returns multiple results for selection)"
  fields:
    query:
      description: "Search query for movies or TV shows (can include titles, actors, genres, etc.)"
      required: true
      example: "Christopher Nolan movies"
      selector:
        text:
  response:
    optional: true

remove_media:
  description: "Remove media from Overseerr with LLM-optimized response (provide title OR media_id)"
  fields:
    title:
      description: "Movie or TV show title to search for and remove (will find media_id automatically)"
      required: false
      example: "The Matrix"
      selector:
        text:
    media_id:
      description: "Direct media ID to remove (from mediaInfo.id in status checks)"
      required: false
      example: "12345"
      selector:
        text:
  response:
    optional: true

get_active_requests:
  description: "Get current active requests with LLM-optimized response (focuses on processing requests, ordered by date)"
  fields: {}
  response:
    optional: true

run_job:
  description: "Trigger a specific Overseerr job with LLM-optimized response"
  fields:
    job_id:
      description: "Job ID to run (available from Jobs Status sensor or get_active_requests)"
      required: true
      example: "availability-sync"
      selector:
        text:
  response:
    optional: true

get_resolved_requests:
  description: "Get completed, failed, and partially available requests with LLM-optimized response"
  fields: {}
  response:
    optional: true