# File: services.yaml
# Note: Keep this filename comment for navigation and organization

test_connection:
  description: "Test connection to Overseerr and get basic information"
  fields: {}
  response:
    optional: true

check_media_status:
  description: "Check media status with LLM-optimized structured response"
  fields:
    title:
      description: "Movie or TV show title to search for"
      required: true
      example: "The Dark Knight"
      selector:
        text:
  response:
    optional: true

add_media:
  description: "Add movie or TV show to Overseerr with LLM-optimized response (auto-detects type, supports season selection for TV shows)"
  fields:
    title:
      description: "Movie or TV show title to search for and add"
      required: true
      example: "Inception"
      selector:
        text:
    season:
      description: "For TV shows: season number (1, 2, 3) or natural language ('season two', 'remaining seasons', 'next season', 'all seasons'). Defaults to season 1 if not specified."
      required: false
      example: "remaining seasons"
      selector:
        text:
    is4k:
      description: "Request movie in 4K quality (only applicable for movies, not TV shows)"
      required: false
      example: true
      default: false
      selector:
        boolean:
  response:
    optional: true

search_media:
  description: "Search for movies and TV shows with LLM-optimized response (returns multiple results for selection)"
  fields:
    query:
      description: "Search query for movies or TV shows (can include titles, actors, genres, etc.)"
      required: true
      example: "Christopher Nolan movies"
      selector:
        text:
  response:
    optional: true

remove_media:
  description: "Remove media from Overseerr with LLM-optimized response (provide title OR media_id)"
  fields:
    title:
      description: "Movie or TV show title to search for and remove (will find media_id automatically)"
      required: false
      example: "The Matrix"
      selector:
        text:
    media_id:
      description: "Direct media ID to remove (from mediaInfo.id in status checks)"
      required: false
      example: "12345"
      selector:
        text:
  response:
    optional: true

get_requests:
  description: "Get requests with LLM-optimized response (supports filtering by status and pagination)"
  fields:
    filter:
      description: "Filter requests by status (all, available, partial, allavailable, processing, pending, deleted)"
      required: false
      example: "all"
      default: "all"
      selector:
        select:
          options:
            - "all"
            - "available"
            - "partial"
            - "allavailable"
            - "processing"
            - "pending"
            - "deleted"
    take:
      description: "Number of results to return (page size)"
      required: false
      example: 100
      default: 100
      selector:
        number:
          min: 1
          max: 500
    skip:
      description: "Number of results to skip (for pagination)"
      required: false
      example: 0
      default: 0
      selector:
        number:
          min: 0
          max: 2000
  response:
    optional: true

run_job:
  description: "Trigger a specific Overseerr job with LLM-optimized response"
  fields:
    job_id:
      description: "Job ID to run (available from Jobs Status sensor or get_active_requests)"
      required: true
      example: "availability-sync"
      selector:
        text:
  response:
    optional: true

get_resolved_requests:
  description: "Get completed, failed, and partially available requests with LLM-optimized response"
  fields: {}
  response:
    optional: true

get_media:
  description: "Get media from library with LLM-optimized response (uses /api/v1/media endpoint for comprehensive view)"
  fields:
    filter:
      description: "Filter media by status (all, available, partial, allavailable, processing, pending, deleted)"
      required: false
      example: "all"
      default: "all"
      selector:
        select:
          options:
            - "all"
            - "available"
            - "partial"
            - "allavailable"
            - "processing"
            - "pending"
            - "deleted"
    take:
      description: "Number of results to return (page size)"
      required: false
      example: 50
      default: 50
      selector:
        number:
          min: 1
          max: 200
    skip:
      description: "Number of results to skip (for pagination)"
      required: false
      example: 0
      default: 0
      selector:
        number:
          min: 0
  response:
    optional: true